WebShop2018/Controllers/ArtikliController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebShop2018.Models;
using System.Linq.Dynamic;
using System.IO;
using System.Net;

namespace WebShop2018.Controllers
{
    [Authorize]
    public class ArtikliController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Artikli
        [AllowAnonymous]
        public ActionResult Index(ArtikliGridViewModel viewModel)
        {
            IQueryable<Proizvod> proizvodi = db.Proizvodi;
            if (viewModel.Query != null)
            {
                // daj sve proizvode gde ime sadrzi ovaj query parametar
                proizvodi = proizvodi.Where(p => p.Naziv.Contains(viewModel.Query));
            }
            if (viewModel.MaxPrice.HasValue)
            {
                // svi proizvodi koji imaju cenu manju od
                proizvodi = proizvodi.Where(p => p.Cena <= viewModel.MaxPrice);
            }
            if (viewModel.SortBy != null && viewModel.SortDirection != null)
            {
                // sortiranje koriscenjem Linq.Dynamic
                proizvodi = proizvodi.OrderBy(string.Format("{0} {1}", viewModel.SortBy, viewModel.SortDirection));
            }

            // uzmemo ukupan broj proizvoda iz baze koji zaovoljavaju kriterijume pretrage
            viewModel.Count = proizvodi.Count();

            // paging
            proizvodi = proizvodi.Skip((viewModel.Page - 1) * viewModel.PageSize).Take(viewModel.PageSize);

            // vrati podatke iz baze :)
            viewModel.Artikli = proizvodi.ToList();

            if (User.IsInRole(RolesConfig.USER))
            {
                viewModel.Order = db.Orders.FirstOrDefault(o => o.State == OrderState.Open &&
                    o.User.UserName == User.Identity.Name);
            }


            // vracamo view sa view modelom
            return View(viewModel);
        }

        // GET
        [Authorize(Roles = RolesConfig.ADMIN)]
        public ActionResult Create()
        {
            @ViewBag.Title = "Create";
            PostaviKategorije();
            return View();
        }

        [HttpPost]
        [Authorize(Roles = RolesConfig.ADMIN)]
        public ActionResult Create(Proizvod proizvodIzForme, HttpPostedFileBase slika)
        {
            if (ModelState.IsValid)
            {
                //snimanje u bazu
                proizvodIzForme.Kategorija = db.Kategorije.Find(proizvodIzForme.Kategorija.Id);
                db.Proizvodi.Add(proizvodIzForme);
                db.SaveChanges();

                

                // drugi save changes nam snima ime slike
                db.SaveChanges();

                //ako je sve uredu salje na index akciju (lista proizvoda)
                return RedirectToAction("Index");
            }

            // vraca formu sa podacima u slucaju greske
            ViewBag.Title = "Create";
            PostaviKategorije();
            return View(proizvodIzForme);
        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proizvod proizvod = db.Proizvodi.Find(id);
            if (proizvod == null)
            {
                return HttpNotFound();
            }
            return View(proizvod);
        }

        public void UploadPicture(IEnumerable<HttpPostedFileBase> slika, Proizvod modelToUpdate, string opis)
        {

            if (slika != null)
            {
                foreach (var file in slika)
                {
                    if (file.ContentLength > 0)
                    {
                        var postojecaSlika = db.Slike.FirstOrDefault(o => o.Naziv == file.FileName && o.proizvod.Id == modelToUpdate.Id);
                        if (postojecaSlika == null)
                        {
                            var sl = new Slike()
                            {

                                Naziv = file.FileName,
                                proizvod = modelToUpdate,
                                Opis = opis

                            };
                            db.Slike.Add(sl);

                            var putanjaDoFoldera = Server.MapPath(string.Format("~/Content/vezbaSlike/{0}{1}", modelToUpdate.Id, file.FileName));
                            //var putanjaDoFoldera = Server.MapPath(string.Format($"~/Content/vezbaSlike/{modelToUpdate.NoImage}"));
                            file.SaveAs(putanjaDoFoldera);
                        }



                    }
                }
            }
        }

        [Authorize(Roles = RolesConfig.ADMIN)]
        public ActionResult Edit(int id)
        {
            var proizvodIzBaze = db.Proizvodi.Find(id);

            //vraca 404 ako proizvod nije nadjen
            if (proizvodIzBaze == null)
            {
                return HttpNotFound();
            }

            ViewBag.Title = "Edit";
            PostaviKategorije();
            return View("Create", proizvodIzBaze);
        }

        [HttpPost]
        [Authorize(Roles = RolesConfig.ADMIN)]
        public ActionResult Edit(Proizvod proizvodIzForme, IEnumerable<HttpPostedFileBase> slika, string opis)
        {
            if (ModelState.IsValid)
            {
                //nadji proizvod iz baze
                var proizvodIzBaze = db.Proizvodi.Find(proizvodIzForme.Id);
                //update vrednostima iz forme
                TryUpdateModel(proizvodIzBaze, new string[] { "Naziv", "Cena", "Stanje" });
                //dodela kategorije
                proizvodIzBaze.Kategorija = db.Kategorije.Find(proizvodIzForme.Kategorija.Id);

                UploadPicture(slika, proizvodIzBaze, opis);

                //snimi u bazu
                db.SaveChanges();

                //vrati na listu ako je sve u redu
                return RedirectToAction("Index");
            }

            ViewBag.Title = "Edit";
            PostaviKategorije();
            return View("Create", proizvodIzForme);
        }
        public ActionResult DeletePicture(int id)
        {
            //uzmemo sliku koju brisemo
            var slikaZaBrisanje = db.Slike.Find(id);
            var proizvodId = slikaZaBrisanje.proizvod.Id;

            //brisemo iz fajl sistema
            var fileName = string.Format("{0}{1}", proizvodId, slikaZaBrisanje.Naziv);
            var filePath = Server.MapPath($"~/Content/vezbaSlike/{fileName}");
            if (System.IO.File.Exists(filePath))
            {
                System.IO.File.Delete(filePath);
            }

            //brisemo iz baze
            db.Slike.Remove(slikaZaBrisanje);
            db.SaveChanges();
            

            return RedirectToAction("Details", new { id = proizvodId });
        }
        //get
        public ActionResult AddPicture(int id)
        {
            var pro = db.Proizvodi.Find(id);

            if (pro == null)
            {
                return HttpNotFound();
            }

            return View("AddPicture");
        }
        [HttpPost]
        public ActionResult AddPicture(int id, IEnumerable<HttpPostedFileBase> slika, string opis)
        {
            ViewBag.Text = "AddPicture";
            var modelToUpdate = db.Proizvodi.Find(id);

            if (ModelState.IsValid)
            {


                UploadPicture(slika, modelToUpdate, opis);
                db.SaveChanges();

            }

            return RedirectToAction("Details", new { id = modelToUpdate.Id });
        }
       // get
        public ActionResult EditPicture(int id, string ime)
        {
            var slika = db.Slike.Find(id);
            var idProizvoda = slika.proizvod.Id;
            var proizvod = db.Proizvodi.Find(idProizvoda);


            if (proizvod == null)
            {
                return HttpNotFound();
            }

            return View("EditPicture");
        }
        [HttpPost]
        public ActionResult EditPicture(int id, IEnumerable<HttpPostedFileBase> slika, string opis)
        {

           // slika za brisanje
            var slikaZaDelete = db.Slike.Find(id);
            var idProizvoda = slikaZaDelete.proizvod.Id;
            var proizvod = db.Proizvodi.Find(idProizvoda);

            ViewBag.Text = "EditPicture";

            if (ModelState.IsValid)
            {

                UploadPicture(slika, proizvod, opis);

                var fileName = string.Format("{0}{1}", idProizvoda, slikaZaDelete.Naziv);
                var filePath = Server.MapPath($"~/Content/vezbaSlike/{fileName}");
                if (System.IO.File.Exists(filePath))
                {
                    System.IO.File.Delete(filePath);
                }
                db.Slike.Remove(slikaZaDelete);
                db.SaveChanges();
                return RedirectToAction("Details", new { id = idProizvoda });
            }

            return View();
        }

        [Authorize(Roles = RolesConfig.ADMIN)]
        [HttpDelete]
        public ActionResult Delete(int id)
        {
            var proizvodIzBaze = db.Proizvodi.Find(id);

            //var orderLinesForDelete = db.OrderLines.Where(ol => ol.Item.Id == proizvodIzBaze.Id);
            //db.OrderLines.RemoveRange(orderLinesForDelete);

            db.Proizvodi.Remove(proizvodIzBaze);

            try
            {
                db.SaveChanges();
            }
            catch (Exception ex)
            {
                // logujemo exception ili tako nesto
                return new HttpStatusCodeResult(500);
            }

            return new HttpStatusCodeResult(200);
        }

        public void PostaviKategorije()
        {
            ViewBag.Kategorije = db.Kategorije.ToList();
        }

        [Authorize(Roles = RolesConfig.USER)]
        public ActionResult AddToCart(int id)
        {

WebShop2018/Views/Artikli/AddPicture.cshtml
@model WebShop2018.Models.Slike
@{

}

<h2>AddPicture</h2>
@using (Html.BeginForm("AddPicture", "Artikli", FormMethod.Post, new { enctype = "multipart/form-data" }))
{





    @Html.LabelFor(m => m.Opis)
    @Html.EditorFor(m => m.Opis)
    @Html.ValidationMessageFor(m => m.Opis)
    <br />

    <input name="slika" type="file" accept="image/*" />



    <input type="submit" value="Create" />

}

WebShop2018/Views/Artikli/Create.cshtml
@model WebShop2018.Models.Proizvod

<h2>@ViewBag.Title</h2>

@Html.ActionLink("Back", "Index")

@*moramo da stavimo encoding za formu da bi poslali slliku (enctype = "multipart/form-data")*@
@using (Html.BeginForm((string)ViewBag.Title, "Artikli", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.LabelFor(m => m.Naziv)
    @Html.EditorFor(m => m.Naziv)
    @Html.ValidationMessageFor(m => m.Naziv)

    <br />
    @Html.LabelFor(m => m.Cena)
    @Html.EditorFor(m => m.Cena)
    @Html.ValidationMessageFor(m => m.Cena)

    <br />
    @Html.LabelFor(m => m.Stanje)
    @Html.EnumDropDownListFor(m => m.Stanje)
    @Html.ValidationMessageFor(m => m.Stanje)

    <br />
    @Html.LabelFor(m => m.Kategorija)
    @Html.DropDownListFor(m => m.Kategorija.Id,
                            new SelectList(ViewBag.Kategorije, "Id", "Naziv")
                          )
    @Html.ValidationMessageFor(m => m.Kategorija)

    <br />
    <label>Slika</label>
    <input name="slika" type="file"accept="image/*" multiple="multiple"/>

    <br />
    <input type="submit" value="Save"/>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebShop2018/Views/Artikli/Details.cshtml
@using WebShop2018.Models
@model WebShop2018.Models.Proizvod

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Proizvod</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cena)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cena)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Stanje)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Stanje)
        </dd>
        <dd>
            @Html.ActionLink("Add New Picture", "AddPicture", new { id = Model.Id })
        </dd>

    </dl>
</div>


<table class="table">
    <tr>
        @foreach (var item in Model.slike)
        {

            <td>
                <img src="@string.Format("/Content/vezbaSlike/{0}{1}",item.proizvod.Id,item.Naziv)" width="200" height="200" />
                <br />
                @if (User.IsInRole(RolesConfig.ADMIN))
                {
                    @Html.ActionLink("Edit", "EditPicture", new { id = item.Id })
                    @Html.Raw("|")
                    @Html.ActionLink("Delete", "DeletePicture", new { id = item.Id })
                }
            </td>
        }
    </tr>
</table>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

WebShop2018/Views/Artikli/EditPicture.cshtml
@model WebShop2018.Models.Slike

@{
    @ViewBag.Text
}




@using (Html.BeginForm("EditPicture", "Artikli", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Slike</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Opis, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Opis, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Opis, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input name="slika" type="file" accept="image/*" />
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

WebShop2018/Views/Artikli/Index.cshtml
@using WebShop2018.Models
@model WebShop2018.Models.ArtikliGridViewModel

@{
    ViewBag.Title = "View";
}

<h2>Ukupno proizvoda: @Model.Count</h2>

@using (Html.BeginForm())
{
    <p>
        Ime sadrzi: @Html.TextBox("query")
        Cena do: @Html.TextBox("maxPrice")
        <input type="submit" value="Search" />
    </p>
}

@if (User.IsInRole(RolesConfig.ADMIN))
{
    @Html.ActionLink("Create New", "Create")
}

@if (User.IsInRole(RolesConfig.USER) && Model.Order != null)
{
    @Html.Raw($"<b>Narucili ste {Model.Order.TotalItems} artikla. Vas total je: {Model.Order.Total} </b>")
    using (Html.BeginForm("Details", "Orders", FormMethod.Get))
    {
        <p>
            @Html.Hidden("id", Model.Order.Id)
            <input type="submit" value="Naruci" />
        </p>
    }
}



<table class="table">
    <tr>
        <th>
            Slika
        </th>
        <th>
            @Html.ActionLink("Naziv", "Index", Model.GetSortingParameters("Naziv"))
        </th>
        <th>
            @Html.ActionLink("Cena", "Index", Model.GetSortingParameters("Cena"))
        </th>
        <th>
            @Html.ActionLink("Stanje", "Index", Model.GetSortingParameters("Stanje"))
        </th>
        <th>
            @Html.ActionLink("Kategorija", "Index", Model.GetSortingParameters("Kategorija.Naziv"))
        </th>
        <th>
            Akcije
        </th>
    </tr>
@foreach (var proizvod in Model.Artikli)
{
    <tr>
        <td>
            <img src="@string.Format("/Content/Artikli/{0}", proizvod.ImeSlikeZaPrikaz)" style="width:100px;">
        </td>
        <td>
            @proizvod.Naziv
        </td>
        <td>
            @proizvod.Cena
        </td>
        <td>
            @proizvod.Stanje
        </td>
        <td>
            @Html.DisplayFor(p => proizvod.Kategorija.Naziv)
        </td>
        <td>
            @if (Request.IsAuthenticated && User.IsInRole(RolesConfig.ADMIN))
            {
                @Html.ActionLink("Edit", "Edit", new { id = proizvod.Id }, new { @class = "" })
                @Html.Raw("<br/>")
                @Html.ActionLink("Delete", "Delete", new { id = proizvod.Id }, new { @class = "delete-dugme" })
                @Html.Raw("<br/>")
                @Html.ActionLink("Details", "Details", new { id = proizvod.Id })
            }
            @if (User.IsInRole(RolesConfig.USER))
            {
                @Html.ActionLink("Dodaj u korpu", "AddToCart", new { id = proizvod.Id }, new { @class = "" })
            }
        </td>
    </tr>
}
</table>

@Html.Partial("_GridPager", Model)

<!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Error</h4>
            </div>
            <div class="modal-body">
                <p>Delete error!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

@section Scripts{
    <script>
        // jQuery
        $('.delete-dugme').on('click', function () {

            if (confirm("Are you sure?")) {
                var deleteURL = $(this).attr('href');
                $.ajax({
                    url: deleteURL,
                    type: 'DELETE',
                    success: function (result) {
                        // nije dobro resenje
                        $(this).parent().parent().hide();
                        // i ovo nije dobro resenje :)
                        //location.reload();
                    }.bind(this),
                    error: function (result) {
                        $("#myModal").modal("show");
                    }
                });
                
            }
            return false;
        });
    </script>
}